name: Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: configure2
      run: cat /etc/apt/sources.list
    - name: test2
      run: cat /etc/apt/apt-mirrors.txt
