name: Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cat /etc/apt/sources.list.d/ubuntu.sources
    - name: configure2
      run: cat /etc/apt/sources.list
